### PR TITLE
imagemagick update

### PR DESCRIPTION
**Pull request by Villemoes**

### CODE REVIEW

**Review by kimrhh — APPROVED** [review]

**Comment by vmbracvlvm** [comment]
version 6.9.6-7 is no longer available on ftp.nluug.nl :)

**Comment by Villemoes** [comment]
Crazy stuff. I already updated the PR once because 6.9.6-6 vanished on Dec 5, which wasn't that long after the initial PR. We really really need to get our mirroring to work, we can't update imagemagick every week.

**Comment by kimrhh** [comment]
i can manually (*sigh*) add the file to our OE-lite.org mirror: http://oe-lite.org/mirror/ if you still have it? 

making our mirror fetch stuff automatically is a big task as it involves a lot of infra work

**Comment by kimrhh** [comment]
should be there now

**Pull request merged**
